// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.201
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommandTableInfo
{
    static class Vsix
    {
        public const string Id = "1a973c52-a674-48d8-a276-65ddab1ac598";
        public const string Name = "Command Table Info";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Mads Kristensen";
        public const string Tags = "";
    }
}
