// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommandTableInfo
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCommandTablePackageString = "82d76b14-dcc0-423c-8b05-bac944909ebd";
        public static Guid guidCommandTablePackage = new Guid(guidCommandTablePackageString);

        public const string guidCommandTablePackageCmdSetString = "a5bb06f5-7f0a-4194-b06f-0bb25d48f268";
        public static Guid guidCommandTablePackageCmdSet = new Guid(guidCommandTablePackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowToolWindowId = 0x0200;
    }
}