// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommandTableInfo
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCommandTablePackageString = "82d76b14-dcc0-423c-8b05-bac944909ebd";
        public static Guid guidCommandTablePackage = new Guid(guidCommandTablePackageString);

        public const string guidCommandTablePackageCmdSetString = "a5bb06f5-7f0a-4194-b06f-0bb25d48f268";
        public static Guid guidCommandTablePackageCmdSet = new Guid(guidCommandTablePackageCmdSetString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ShowToolWindowId = 0x0200;
        public const int CopyContextValueId = 0x0300;
        public const int CopyVsctSymbolsId = 0x0301;
        public const int DetailsContextMenu = 0x1000;
        public const int HierarchyContextMenu = 0x1001;
        public const int DetailsContextMenuGroup = 0x1100;
        public const int HierarchyContextMenuGroup = 0x1200;
        public const int HierarchyContextMenuVsctSymbolsGroup = 0x1201;
    }
}
